
SealedSecrets:
    clientId: AgB269giCiKkohbFsgeN9Qxqr3DO0/5ajC200hsVY3buiMhAWzBwRMH21/WSvvK+TPkukfuNEG4Dtg+RAWCQsn1qCWrmGasNm2Xf396y+ehBYkudJkFwCUNcjUB5R4tkKi0K+RnEsVJtLIEvzDxNeKBnl50UlbSZQkAyE+vY0+q3wEBwmOMV98btzGraWXebCjhEpZnAkxrLJFXaRs3WmF/HwcMnaShBv1a6CODaoqxz9x85OrFN5Ih/S3DtQE+DUk6oxAUG2aimL04nYvL27WrY/QhahZfEzQc+b2u4hbtzSmyZYawS9dq7KcscMP8kA5ZleDuW6zx+jACmHF0u+SLDyIUgXVRUijtQBaqLdqAqVBdUB7O6QYRDlEYAS54PaerL+e5Zpz3zK80bFLtbEGMKoUYsH5BUn74p3c55nd0Tr/l3YYetUJQn3NZaVLlX1YNbzAqo+jYftZw53oR7SuKWpIog+CRK53a4DlNu0gB5UaTVAHyhttJ95FRz31TLZliXglYQXaKl0UmgCZ11CzAOJes0pO+rHRZq776kQgfrr25C0gAHC0RpFzO94dLYQnqY2IfDDOir5jpkEq+U3/BMM6eMX1T4LRjG65kh2jbe5WZ+rne9PaS7CDKK1/BBIkC/wjv7zJWVqraC1jyrCSHsUgpWHJCUP2adsVnfwUPZ20iIqroxDWbslrzq5Aiu6nGFhA3EDD7RO1zRw8Fqer7KTJLxhQ==
    clientSecret: AgBbjMfp/VV2HUKLc0tZnfjIP3rcoWI/ljjUdOM7/9utulcGTQGijg/Q2gwu0in1j82y2LMFzees0SncsuQzQkjyrdiKUnQ0za1oehGke2zCMepTOavYMnbTaaoIaTssRhZHe9M820fY7JKJ49X2LlPdRo2WMTIdk/nMkpTWZsAMfV5/TY9Aj+GO8DxEejEsgJlecZhSe/ORnEnYtqtH0XQ7okOhZVzXXWX1f9GrngUuF27BHOmBRSuJfhL0RCj8jLtsj48DYgJIZJNyoIsjXhVFzazvEI89gK/QWWsRcvxKUQ1uEgKzGam5lo+2/aAYqkTFFflIDr3cQsEyTE4cbiLyvpuUDJYup+Hvf2bHht1ZUFa6kk3KODqV0CrPKYrkHurHZFhBWBVsBezolBLXdZbEuMgcEsS5e0OfYm9MEc/H2+GAoUyk2xTU+5Wfg83nsTYNsByBMUD7mKNh6r7QsiuO0FHcbDw6Odxy+I/USARFFox0zq/Kwc9+PPgsun2UH8jUftonXxkG0wHrK5FcQNh2nJ300bYWHG/ozkkX1YzOBZ0TN1X6LSuVj1tr1h0a9SpeBIxfwRAwCnB5oqxfnnt4ZWAwbAcFZs+f9sYHAAJZYip8VxY4PSRQXG0I1VAHFjav1eNRIcP6YYFCxsApA51KOVoZteb37sztNqgyOycuUk/KJ3oZ63GxvalUFIS3s9sa3TvUjLCI2Zx+hrNLB1mRcP3lP/YrFqsjmO8OzAmCEj8yZMp8uBOm
    cookieSecret: AgBzJO1Nh+sEIsS1+tMZfxPgNa4cZico2OccRmdebxL4uEedJSsZ29UvznvBTx+0KXfoPE25onP8ih8pAYOEyhvuDVUwxDA0zRvwIeHPvVQCVORBnjvxJxjjqP/PDHLPXGiu4mqYgC41mGX5KO/I4Oy+mG/hvd2EUXbgF+yAZ+HcXMp9XZXodzTA31432fszft7RdA0bxdihTW99ovFfitDF4VKAZ6eDwAD1DLNEvOq4JGEFhjNWiVmAnuaAbQGh365zF8d7VM5AQEplPE3NV+RKw8h2TI0sXJEOquaslDuwVDVIaCWEpXpHjXHquZdvYn9FWZmNjQQcpdLzhWZjSkbMO8S9EGv8+z80Teh3Y6QC0WXl4TFZplA9AWb7sjWn0GsWjcyy9XIdcQ6KxzDkapibkdPAs4tyGEufD4vHx6JSXEwze5EUbERRKmTHAPA07X/dlm9n4a8M8KyUMnDryQBJsSnl5+l0l+WO5+mmJKdJw3on7VVsp6tQTI5ac4n5Gajm8uBhbud1wETTWu6fG3bBK9AMXPvLaQqE7rjpqCy2qTC8PNSdpPvYxcvwKJ8IwnXTWdhsFU+pXWqFQhGtzrXR0FkPOPHov3xeIdoWHLyeappQxcHTLiUqE/hIBitdpu6DOIAeT42pwTjwSoaY+k+0Fmy6E1Os6UK7QMIZVoJQojXZd/WjjPWpBEsyXgqmLulXZaqiBO3PLfWWr6wy/+FqW98+JsuAQeL9mdo6tTxCxg==
 
oauth2-proxy:
  config:
    existingSecret: "oauth2-secret"
    configFile: |
      provider = "github"
      github_org = "mina-basta"
      email_domains = [ "*" ]
      cookie_domains = [ "datavisyn.online" ]
      cookie_expire = "1d"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      acme.cert-manager.io/http01-edit-in-place: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - datavisyn.online
    path: /oauth2
    pathType: Prefix
